# Generated by Django 5.2.5 on 2025-08-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_diary_session_key_alter_diary_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='llm_model',
            field=models.CharField(default='gpt-4o-mini', max_length=100),
        ),
        migrations.AddField(
            model_name='diary',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini')], default='openai', max_length=50),
        ),
    ]
